#!/bin/bash
pin="2022"
echo -n " please enter your pinnumber"
exit status 0 or 1 1st in control scripting
elseif elif

can a deleted file or directory be recovered (like in recyccle bin)
any command that performs the function of "undo"